[package]
name = "jinnie-ai"
version = "0.1.0"
edition = "2021"
description = "100% Rust-powered AI assistant with local processing"
license = "MIT"
authors = ["Your Name <your.email@example.com>"]

[[bin]]
name = "jinnie-ai"
path = "src/main.rs"

[dependencies]
# ============================================================================
# CORE ASYNC RUNTIME & UTILITIES
# ============================================================================
tokio = { version = "1.40", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# ============================================================================
# DIOXUS UI FRAMEWORK
# ============================================================================
dioxus = { version = "0.5", features = ["desktop", "router"] }
dioxus-desktop = "0.5"
dioxus-router = "0.5"
dioxus-hot-reload = { version = "0.5", optional = true }

# ============================================================================
# LOGGING & ERROR HANDLING
# ============================================================================
log = "0.4"
env_logger = "0.11"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
thiserror = "1.0"

# ============================================================================
# SERIALIZATION & DATA FORMATS
# ============================================================================
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = { version = "0.9", optional = true }
toml = { version = "0.8", optional = true }
bincode = { version = "1.3", optional = true }
rmp-serde = { version = "1.3", optional = true }

# ============================================================================
# AI & MACHINE LEARNING
# ============================================================================
# Candle - Pure Rust neural network framework (using correct versions)
candle-core = { version = "0.4.1", optional = true }
candle-nn = { version = "0.4.1", optional = true }
candle-transformers = { version = "0.4.1", optional = true }

# Tokenizers and model hub
tokenizers = { version = "0.15", optional = true, default-features = false, features = ["onig"] }
hf-hub = { version = "0.3", optional = true, features = ["tokio"] }

# Additional AI options
ort = { version = "2.0.0-rc.2", optional = true, default-features = false }

# LLM functionality
llm = { version = "0.1", optional = true }

# ============================================================================
# VECTOR DATABASE & EMBEDDINGS
# ============================================================================
qdrant-client = { version = "1.10", optional = true }
uuid = { version = "1.10", features = ["v4", "serde"] }

# ============================================================================
# DATABASE & STORAGE
# ============================================================================
rusqlite = { version = "0.32", features = ["bundled"] }
rocksdb = { version = "0.22", optional = true, default-features = false }
redb = { version = "2.1", optional = true }

# ============================================================================
# AUDIO PROCESSING (OPTIONAL)
# ============================================================================
rodio = { version = "0.19", optional = true }
cpal = { version = "0.15", optional = true }
hound = { version = "3.5", optional = true }
symphonia = { version = "0.5", optional = true, default-features = false }

# ============================================================================
# FILE PROCESSING (OPTIONAL)
# ============================================================================
# PDF processing
lopdf = { version = "0.30", optional = true }
pdf-extract = { version = "0.7", optional = true }

# Office documents
calamine = { version = "0.22", optional = true }
docx-rs = { version = "0.4", optional = true }

# Image processing
image = { version = "0.25", optional = true }
imageproc = { version = "0.25", optional = true }

# Archive handling
zip = { version = "2.1", optional = true, default-features = false, features = ["deflate"] }
tar = { version = "0.4", optional = true }
flate2 = { version = "1.0", optional = true }

# ============================================================================
# HTTP CLIENT & NETWORKING
# ============================================================================
reqwest = { version = "0.11", features = ["json", "stream"] }
url = "2.5"

# ============================================================================
# SYSTEM INTEGRATION (OPTIONAL)
# ============================================================================
notify = { version = "6.1", optional = true }
clipboard = { version = "0.5", optional = true }
sysinfo = { version = "0.31", optional = true }

# ============================================================================
# CRYPTOGRAPHY & SECURITY
# ============================================================================
sha2 = "0.10"
blake3 = "1.5"
rand = "0.8"

# ============================================================================
# TIME & DATE
# ============================================================================
chrono = { version = "0.4", features = ["serde"] }
time = "0.3"

# ============================================================================
# TEXT PROCESSING
# ============================================================================
regex = "1.10"
once_cell = "1.19"
lazy_static = "1.4"

# ============================================================================
# UI COMPONENTS
# ============================================================================
dirs = "5.0"

# ============================================================================
# FEATURES
# ============================================================================
[features]
default = []

# Development features
dev = ["dioxus-hot-reload"]

# Core AI features
basic-ai = ["candle-core", "candle-nn", "tokenizers"]
transformers = ["basic-ai", "candle-transformers"]
vector-db = ["qdrant-client"]
model-hub = ["hf-hub"]
llm-support = ["llm"]

# Extended AI features
full-ai = ["transformers", "vector-db", "model-hub", "llm-support"]
onnx = ["ort"]

# Audio processing
audio = ["rodio", "cpal", "hound"]
full-audio = ["audio", "symphonia"]

# File processing
pdf = ["lopdf", "pdf-extract"]
office = ["calamine", "docx-rs"]
images = ["image", "imageproc"]
archives = ["zip", "tar", "flate2"]
full-docs = ["pdf", "office", "images", "archives"]

# Database options
advanced-db = ["rocksdb", "redb"]

# System integration
system = ["notify", "clipboard", "sysinfo"]

# Serialization formats
formats = ["serde_yaml", "toml", "bincode", "rmp-serde"]

# All features (for testing)
all-features = [
    "full-ai", "onnx", "full-audio", "full-docs", 
    "advanced-db", "system", "formats", "dev"
]

# ============================================================================
# BUILD PROFILES
# ============================================================================
[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
debug = false
strip = true
lto = true
codegen-units = 1
panic = "abort"

# ============================================================================
# DEVELOPMENT DEPENDENCIES
# ============================================================================
[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
tempfile = "3.10"

# ============================================================================
# BUILD DEPENDENCIES
# ============================================================================
[build-dependencies]