[package]
name = "local-ai-agent"
version = "0.1.0"
description = "LocalMind - Privacy-focused AI Agent with Knowledge Transfer"
authors = ["LocalMind Team"]
license = "MIT"
repository = "https://github.com/your-org/localmind"
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
# Core Tauri dependencies
tauri = { version = "1.5.0", features = ["api-all", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"

# File system
dirs = "5.0"

# System information
sysinfo = "0.29"

# Compression (for knowledge transfer)
flate2 = "1.0"

# Basic encryption (can be enhanced later)
base64 = "0.21"

[features]
# By default, we'll use all Tauri features for development
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]