[package]
name = "local-ai-agent"
version = "0.1.0"
description = "LocalMind AI Agent - Privacy-focused local AI assistant"
authors = ["LocalMind Team"]
license = "MIT"
repository = "https://github.com/yourusername/localmind"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
# Core Tauri framework
tauri = { version = "1.5", features = [ "clipboard-all", "process-relaunch", "process-exit", "global-shortcut-all", "window-all", "http-request", 
    "system-tray", 
    "dialog-all", 
    "fs-all", 
    "shell-open",
    "notification-all",
    "os-all",
    "path-all"
] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# HTTP client for Ollama API
reqwest = { version = "0.11", features = ["json"] }

# Unique identifiers
uuid = { version = "1.0", features = ["v4", "serde"] }

# Date and time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"

# Environment logging
env_logger = "0.10"

# System information
sysinfo = "0.29"

# Directory utilities
dirs = "5.0"

# Base64 encoding (for knowledge transfer)
base64 = "0.21"

[features]
# This feature is used for production builds or when `devPath` points to the filesystem
custom-protocol = ["tauri/custom-protocol"]
