[package]
name = "local-ai-agent"
version = "0.1.0"
description = "LocalMind AI Agent - Privacy-focused local AI with knowledge transfer"
authors = ["LocalMind Team"]
license = "MIT"
repository = "https://github.com/your-username/localmind"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
# Core Tauri dependencies
tauri = { version = "1.5", features = [ "global-shortcut-all", "window-all", "system-tray", "process-relaunch", "process-exit", "path-all", "os-all", "dialog-all", "notification-all", "http-request", "clipboard-all", "fs-all", "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Async runtime
tokio = { version = "1", features = ["full"] }

# HTTP client for Ollama API
reqwest = { version = "0.11", features = ["json"] }

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# Date/time handling
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"

# File system utilities
dirs = "5.0"

# Logging
log = "0.4"
env_logger = "0.10"

# System information
sysinfo = "0.29"

[features]
# This feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
default = []
