[package]
name = "local-ai-agent"
version = "0.1.0"
description = "Local AI Agent with OS Integration"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [
    "api-all",
    "dialog-all",
    "fs-all",
    "shell-all",
    "system-tray",
    "notification-all",
    "window-all"
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
dirs = "5.0"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
futures = "0.3"
sysinfo = "0.30"

# Vector database
chroma-rs = "0.1"

# Compression and encryption
flate2 = "1.0"
zstd = "0.13"
aes-gcm = "0.10"
rand = "0.8"

# For local embeddings
candle-core = "0.4"
candle-nn = "0.4"
candle-transformers = "0.4"
hf-hub = "0.3"
tokenizers = "0.15"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]